### 第1章 矩阵与方程组


In [2]:
import pandas as pd
import numpy as np
import matplotlib as mplot

1. 方程求幂 P45
    
设
    $$ A = \begin{bmatrix} 1 & 1 \\ 1 & 1 \\  \end{bmatrix}$$
一般情况：
    $$ A^n = \begin{bmatrix} 2^{n-1} & 2^{n-1} \\2^{n-1} & 2^{n-1} \\ \end{bmatrix} $$


In [21]:
#创建全0矩阵
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [20]:
#创建全1矩阵
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [22]:
#点积
np.dot(np.dot(ones,ones),ones,)

array([[4., 4.],
       [4., 4.]])

In [23]:
np.dot(ones,np.dot(ones,ones),)

array([[4., 4.],
       [4., 4.]])

In [24]:
#单位矩阵
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2],[3, 4],[5,6]])

In [26]:
#矩阵乘以单位矩阵
np.dot(a,i)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
#转置矩阵
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
#P51
A = np.array([[0,1,0,0,0],
[1,0,0,0,1],
[0,0,0,1,1],
[0,0,1,0,1],
[0,1,1,1,0],
])
np.dot(A,np.dot(A,A))

array([[0, 2, 1, 1, 0],
       [2, 0, 1, 1, 4],
       [1, 1, 2, 3, 4],
       [1, 1, 3, 2, 4],
       [0, 4, 4, 4, 2]])

In [31]:
np.dot(A,A)

array([[1, 0, 0, 0, 1],
       [0, 2, 1, 1, 0],
       [0, 1, 2, 1, 1],
       [0, 1, 1, 2, 1],
       [1, 0, 1, 1, 3]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.mat(a)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [35]:
np.mat(a).I

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

In [37]:
np.mat(a).T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [50]:
m1 = np.linspace(1,9,9).reshape((3,3))
m1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [48]:
m2 = np.matmul(m1,m1)

In [49]:
m2

array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]])

In [51]:
m1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [53]:
a7= np.matrix([[1/2,-1/2],[-1/2,1/2]])
a7

matrix([[ 0.5, -0.5],
        [-0.5,  0.5]])

In [85]:
np.dot(a7, np.dot(a7,a7))

matrix([[ 0.5, -0.5],
        [-0.5,  0.5]])

In [86]:
a8 = np.eye(4)
a8[a8>0] = 1/2
a8[a8==0] = -1/2
a8

array([[ 0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5]])

In [87]:
np.dot(a8,np.dot(a8,a8))

array([[ 0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5]])

In [67]:
a10 = np.diag((3.0,2.0,3.0))

In [69]:
np.linalg.eig(a10)

(array([3., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [88]:
a10

array([[ 0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5]])

In [89]:
np.linalg.inv(a10)

array([[ 0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5]])

In [79]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [92]:
#求逆矩阵
A_0 = np.matrix([[1,2,1],[2,5,3],[2,3,2]])
A_1 = np.linalg.inv(A_0)
A_1

matrix([[ 1., -1.,  1.],
        [ 2., -0., -1.],
        [-4.,  1.,  1.]])

In [93]:
A_0

matrix([[1, 2, 1],
        [2, 5, 3],
        [2, 3, 2]])

In [94]:
np.linalg.inv(A_1)

matrix([[1., 2., 1.],
        [2., 5., 3.],
        [2., 3., 2.]])

In [95]:
A_0 * A_1

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])